### ISSUE TITLE
FastCGI

### ISSUE THREAD

**Issue by martijngastkemper** [ficusio/openresty#4]
Is there particular reason why the flag --without-http_fastcgi_module is used. I want to run a PHP application behind a Open Resty / Nginx front-end server.

**Comment by skozin** [comment]
Hi @martijngastkemper, I am really sorry for the delay and for being such a bad maintainer.

No, no particular reason except we don't need FastCGI in our setup and wanted to keep as few modules as possible to keep memory footprint low. But this is such a frequently used module that excluding it is indeed a bad idea.
